name: Python Tests

on: [push]

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==1.1.11"
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Test with pytest
        run: |
          poetry run pytest --verbose --color=no
